# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        Flag_image:
            uri_prefix: /images/flags
            upload_destination: '%kernel.project_dir%/public/images/flags'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer